{% set name = "orca" %}
{% set version = "1.3.1" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 25ebf207d75769c140dcea033a984e7a3a6d919bb8e110a14c890c8cf430f14d
  patches:
    - packagelock_7zipbin.patch

build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - nodejs

test:
  commands:
    - orca --help

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - rluria14
    - oblute
