{% set name = "orca" %}
{% set version = "4.1.0" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 62b640ba345ff138358b6625d2cbc876fcf0f2a1a8bc551d82d12ffb494d01c0

build:
  number: 0
  binary_relocation: false
  skip: true  # [linux]

requirements:
  build:
    - nodejs

test:
  commands:
    - orca --help

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - rluria14
    - oblute
