{% set name = "orca" %}
{% set version = "3.4.2" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d527c4dafb8d4b899f77753eb7ce56640d116a4ba4241a7ec732cba774cfc9eb

build:
  number: 0
  noarch: generic
  script:
    npm pack
    mkdir -p $PREFIX/lib

    if [[ "$OSTYPE" == "darwin"* ]]; then
      # Mac OSX
      mv release/mac/orca.app $PREFIX/lib
    else
      # Assume Linux
      mv release/linux-unpacked/ $PREFIX/lib/orca_app
    fi

    mkdir -p $PREFIX/bin
    ORCA_ENTRY=$PREFIX/bin/orca
    cp $RECIPE_DIR/bin/orca $ORCA_ENTRY
    chmod +x $ORCA_ENTRY

requirements:
  build:
    - nodejs
#  run:
#    - gtk3
#    - xorg-libxi
#    - xorg-libxcursor
#    - xorg-libxdamage
#    - xorg-libxcomposite
#    - xorg-libxrandr

test:
  commands:
    - orca --help
    - npm list -g orca
  requires:
    - nodejs

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - rluria14
    - oblute
