{% set name = "orca" %}
{% set version = "4.1.4" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 79a6cc82a5c13b4bb666d5f20860604fa20eff137a70250fd67df3ab90586936

build:
  number: 3
  binary_relocation: false
  skip: true  # [linux]

requirements:
  build:
    - nodejs

test:
  commands:
    - orca --help

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
